"""auth_credentials table init

Revision ID: 20141dec1289
Revises:
Create Date: 2025-06-09 09:25:46.022261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "20141dec1289"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_credentials_login"),
        "auth_credentials",
        ["login"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_credentials_login"), table_name="auth_credentials")
    op.drop_table("auth_credentials")
    # ### end Alembic commands ###
