"""notes table owner_id index

Revision ID: b20d43d55fa1
Revises: 51f9a4778f45
Create Date: 2025-05-06 09:43:10.695540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b20d43d55fa1"
down_revision: Union[str, None] = "51f9a4778f45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_notes_owner_id"), "notes", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notes_owner_id"), table_name="notes")
    # ### end Alembic commands ###
